#!/usr/bin/env python3
"""Assemble the persona/layer-specific plugins declared in plugins.yaml.

The repository root is the canonical source (and the all-in-one
`securable-claude-plugin`). Each plugin in plugins.yaml is generated into
plugins/<name>/ as a self-contained copy — Claude Code copies an installed
plugin into its own cache and a plugin cannot read files outside its own
directory, so every shared asset a plugin cites (data/, templates/, plays/,
references/, schema/, ...) is copied in. The layout mirrors the root, so the
"plugin root is two levels above SKILL.md" rule inside every skill holds
unchanged.

Also generated: plugins/<name>/.claude-plugin/plugin.json (version, author,
license, and repository lockstepped to the canonical manifest),
plugins/<name>/README.md, and the per-plugin entries of
.claude-plugin/marketplace.json (plugins[1:]; plugins[0] stays the
all-in-one entry).

Guards (both modes):
  coverage  every root skill, agent, and command ships in exactly one plugin
  closure   every plugin-root path a shipped file cites (skills/, data/,
            templates/, references/, ...) resolves inside that plugin; a
            skills/ or plays/ reference to something another plugin ships
            is allowed as a soft cross-plugin route, and paths listed under
            repo_only in plugins.yaml (repository tooling named in comments)
            are exempt

Modes:
  (default)   regenerate plugins/ and the marketplace entries
  --check     verify committed output matches; exit 1 on drift (CI)
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML is required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "plugins.yaml"
OUT_DIR = REPO / "plugins"
CANONICAL = REPO / ".claude-plugin" / "plugin.json"
MARKETPLACE = REPO / ".claude-plugin" / "marketplace.json"

ALWAYS = ["LICENSE", "references"]
LOCKSTEP_FIELDS = ["version", "author", "homepage", "repository", "license"]

# Plugin-root-relative path citations inside shipped text files.
ROOTS = ("skills|data|templates|plays|references|schema|scripts|rules|core|"
         "hooks|docs|agents|commands|examples")
PATH_REF = re.compile(
    r"(?P<prefix>\$\{CLAUDE_PLUGIN_ROOT\}/|(?:\.\./)+|(?<![\w./${}@-]))"
    rf"(?P<path>(?:{ROOTS})/[A-Za-z0-9_./*<>{{}}-]*)"
)
TEXT_SUFFIXES = {".md", ".json", ".sh", ".py", ".yaml", ".yml"}
# data/ is reference material citing framework sections, not plugin paths;
# the generated README names the repository's build script by design.
CLOSURE_SKIP_PREFIXES = ("data/",)
CLOSURE_SKIP_FILES = {"README.md"}
# Procedure trees another plugin may own: citing them is a soft route.
SOFT_ROUTE_ROOTS = {"skills", "plays"}


class BuildError(Exception):
    pass


def load_config() -> dict:
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    if not isinstance(config, dict) or not isinstance(config.get("plugins"), dict):
        raise BuildError(f"{CONFIG.name}: expected a 'plugins' mapping")
    return config


def expand(rel: str) -> dict[str, Path]:
    """Map every file under a repo-relative file or directory to its source."""
    src = REPO / rel
    if src.is_file():
        return {rel: src}
    if src.is_dir():
        return {
            p.relative_to(REPO).as_posix(): p
            for p in sorted(src.rglob("*"))
            if p.is_file() and "__pycache__" not in p.parts
        }
    raise BuildError(f"{CONFIG.name}: {rel!r} does not exist")


def manifest_for(name: str, spec: dict, canonical: dict, shared_keywords: list) -> dict:
    manifest = {"name": name, "description": " ".join(spec["description"].split())}
    for field in LOCKSTEP_FIELDS:
        if field in canonical:
            manifest[field] = canonical[field]
    keywords = list(dict.fromkeys([*shared_keywords, *spec.get("keywords", [])]))
    manifest["keywords"] = keywords
    return manifest


def readme_for(name: str, spec: dict) -> str:
    def listing(title: str, items: list, fmt) -> str:
        if not items:
            return ""
        return f"\n## {title}\n\n" + "\n".join(fmt(i) for i in items) + "\n"

    return (
        "<!-- Generated by scripts/build_plugins.py from plugins.yaml. Do not edit. -->\n"
        f"# {name}\n\n"
        f"{' '.join(spec['description'].split())}\n\n"
        "Part of the securable engineering plugin family (FIASSE v1.1 / SSEM). "
        "This directory is a generated, self-contained copy of the canonical "
        "sources at the repository root; edit those and rebuild.\n"
        + listing("Skills", spec.get("skills", []), lambda s: f"- `{s}` — `skills/{s}/SKILL.md`")
        + listing("Agents", spec.get("agents", []), lambda a: f"- `{a}` — `agents/{a}.md`")
        + listing("Commands", spec.get("commands", []), lambda c: f"- `/{c}` — `commands/{c}.md`")
        + "\n## Install\n\n"
        "```\n"
        "/plugin marketplace add Securability-Engineering/securable-claude-plugin\n"
        f"/plugin install {name}@securable-claude-plugins\n"
        "```\n\n"
        "Install the persona plugins you need, or the all-in-one "
        "`securable-claude-plugin` — not both, or every skill registers twice.\n"
    )


def plan(config: dict, canonical: dict) -> tuple[dict[str, dict[str, bytes]], list[dict]]:
    """Return {plugin: {relpath: content}} and the marketplace entries."""
    plugins = config["plugins"]
    shared_keywords = config.get("shared_keywords", [])
    outputs: dict[str, dict[str, bytes]] = {}
    entries: list[dict] = []
    for name, spec in plugins.items():
        sources: dict[str, Path] = {}
        for skill in spec.get("skills", []):
            if not (REPO / "skills" / skill / "SKILL.md").is_file():
                raise BuildError(f"{name}: unknown skill {skill!r}")
            sources.update(expand(f"skills/{skill}"))
        for kind in ("agents", "commands"):
            for item in spec.get(kind, []):
                sources.update(expand(f"{kind}/{item}.md"))
        for rel in [*ALWAYS, *spec.get("files", [])]:
            sources.update(expand(rel))
        files = {rel: src.read_bytes() for rel, src in sources.items()}
        manifest = manifest_for(name, spec, canonical, shared_keywords)
        files[".claude-plugin/plugin.json"] = (json.dumps(manifest, indent=2, ensure_ascii=False) + "\n").encode()
        files["README.md"] = readme_for(name, spec).encode()
        outputs[name] = files
        entries.append({
            "name": name,
            "source": f"./plugins/{name}",
            "description": manifest["description"],
            "version": canonical["version"],
            "author": {"name": canonical.get("author", {}).get("name", "")},
            "homepage": canonical.get("homepage", ""),
            "repository": canonical.get("repository", ""),
            "license": canonical.get("license", ""),
            "keywords": manifest["keywords"],
            "category": "security",
        })
    return outputs, entries


def check_coverage(config: dict) -> list[str]:
    errors = []
    kinds = {
        "skills": sorted(p.parent.name for p in (REPO / "skills").glob("*/SKILL.md")),
        "agents": sorted(p.stem for p in (REPO / "agents").glob("*.md")),
        "commands": sorted(p.stem for p in (REPO / "commands").glob("*.md")),
    }
    for kind, names in kinds.items():
        owners: dict[str, list[str]] = {n: [] for n in names}
        for plugin, spec in config["plugins"].items():
            for item in spec.get(kind, []):
                owners.setdefault(item, []).append(plugin)
        for item, where in owners.items():
            if len(where) != 1:
                errors.append(f"coverage: {kind[:-1]} {item!r} ships in {len(where)} plugins {where} (expected exactly 1)")
    return errors


def check_closure(config: dict, outputs: dict[str, dict[str, bytes]]) -> list[str]:
    repo_only = set(config.get("repo_only", []))
    errors = []
    for plugin, files in outputs.items():
        present = set(files)
        elsewhere = {
            rel for other, other_files in outputs.items() if other != plugin
            for rel in other_files if rel.split("/", 1)[0] in SOFT_ROUTE_ROOTS
        }

        def exists(rel: str, pool: set) -> bool:
            # Prefix match also accepts partial citations like data/asvs/V6.* .
            return any(f.startswith(rel) for f in pool)

        for rel, content in sorted(files.items()):
            if (Path(rel).suffix not in TEXT_SUFFIXES or rel.startswith(CLOSURE_SKIP_PREFIXES)
                    or rel in CLOSURE_SKIP_FILES):
                continue
            text = content.decode("utf-8", errors="replace")
            for match in PATH_REF.finditer(text):
                path = re.split(r"[*<>{}]", match.group("path"), 1)[0].rstrip(".,:;)/-")
                if match.group("prefix").startswith(".."):
                    resolved = (Path(rel).parent / match.group("prefix") / path).as_posix()
                    parts: list[str] = []
                    for part in resolved.split("/"):
                        if part == "..":
                            if parts:
                                parts.pop()
                        elif part not in ("", "."):
                            parts.append(part)
                    path = "/".join(parts)
                if path.count("/") < 1 or path in repo_only or exists(path, present):
                    continue
                if exists(path, elsewhere):
                    continue  # soft route to a skill or play another plugin ships
                errors.append(f"closure: plugins/{plugin}/{rel} cites {path!r}, which this plugin does not ship")
    return sorted(set(errors))


def marketplace_text(entries: list[dict]) -> str:
    marketplace = json.loads(MARKETPLACE.read_text(encoding="utf-8"))
    plugins = marketplace.get("plugins") or []
    if not plugins:
        raise BuildError(f"{MARKETPLACE.relative_to(REPO)}: plugins[0] (the all-in-one entry) is required")
    marketplace["plugins"] = [plugins[0], *entries]
    return json.dumps(marketplace, indent=2, ensure_ascii=False) + "\n"


def actual_files(root: Path) -> dict[str, bytes]:
    if not root.is_dir():
        return {}
    return {p.relative_to(root).as_posix(): p.read_bytes() for p in root.rglob("*") if p.is_file()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="verify committed output; exit 1 on drift")
    args = parser.parse_args()

    try:
        config = load_config()
        canonical = json.loads(CANONICAL.read_text(encoding="utf-8"))
        outputs, entries = plan(config, canonical)
        market = marketplace_text(entries)
    except BuildError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    errors = check_coverage(config) + check_closure(config, outputs)

    if args.check:
        on_disk = {p.name for p in OUT_DIR.iterdir() if p.is_dir()} if OUT_DIR.is_dir() else set()
        for stale in sorted(on_disk - set(outputs)):
            errors.append(f"drift: plugins/{stale} is not declared in {CONFIG.name}")
        for name, files in outputs.items():
            actual = actual_files(OUT_DIR / name)
            for rel in sorted(set(files) | set(actual)):
                if rel not in actual:
                    errors.append(f"drift: plugins/{name}/{rel} missing")
                elif rel not in files:
                    errors.append(f"drift: plugins/{name}/{rel} is not generated from the sources")
                elif actual[rel] != files[rel]:
                    errors.append(f"drift: plugins/{name}/{rel} differs from its source")
        if MARKETPLACE.read_text(encoding="utf-8") != market:
            errors.append(f"drift: {MARKETPLACE.relative_to(REPO)} per-plugin entries are stale")
        if errors:
            for line in errors:
                print(f"FAIL {line}", file=sys.stderr)
            print("run: python3 scripts/build_plugins.py", file=sys.stderr)
            return 1
        total = sum(len(f) for f in outputs.values())
        print(f"OK — {len(outputs)} plugins ({total} files) in sync with sources; coverage and closure hold.")
        return 0

    if errors:
        for line in errors:
            print(f"FAIL {line}", file=sys.stderr)
        return 1
    if OUT_DIR.is_dir():
        for child in OUT_DIR.iterdir():
            if child.is_dir():
                shutil.rmtree(child)
    for name, files in outputs.items():
        for rel, content in files.items():
            target = OUT_DIR / name / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
            source = REPO / rel
            if source.is_file() and source.stat().st_mode & 0o111:
                target.chmod(target.stat().st_mode | 0o755)
        print(f"wrote plugins/{name} ({len(files)} files)")
    MARKETPLACE.write_text(market, encoding="utf-8")
    print(f"wrote {MARKETPLACE.relative_to(REPO)} ({len(entries)} per-plugin entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
